#!/bin/sh
#
# PROVIDE: iprd
# KEYWORD: shutdown

. /etc/rc.subr

name=iprd
desc="IP Report Daemon"
rcvar="${name}_enable"
command="/usr/local/sbin/${name}"
iprd_flags="-a"  # iprd args; see iprd -h

start_precmd="${name}_prestart"
iprd_prestart()
{
    rc_flags="${iprd_flags} > /var/log/iprd.log &"
}

load_rc_config $name
run_rc_command "$1"
